name: Main

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'website/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
    paths-ignore:
      - 'website/**'
      - 'README.md'

permissions:
  contents: write

jobs:

  docs:
    runs-on:  ubuntu-latest
    steps:
      - name: Run main
        run: echo "Main running"
