name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: write

jobs:

  check-modified-files:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.set-output.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1
#        with:
#          files: |
#          files_ignore: |
#            website/**
#            README.md

      - name: List modified files
        if: steps.changed-files.outputs.only_modified == 'true'
        run: |
          echo "Modified files:"
          for file in ${{ steps.changed-files.outputs.all_modified }}; do
            echo "$file"
          done

      - name: Run step if only the files listed above change
        id: set-output
        if: steps.changed-files.outputs.only_modified == 'true'
        run: |
          echo "::set-output name=modified_files::${{steps.changed-files.outputs.all_modified}}"

  main:
    runs-on:  ubuntu-latest
    needs: check-modified-files
    if: needs.check-modified-files.outputs.modified_files
    steps:
      - name: Run main
        run: echo "Main running"

  website:
    needs: main
    uses: 'jan-molak/github-actions-independent-workflows/.github/workflows/website.yaml@main'
