name: Main Workflow

on:
  workflow_call:
    input:
      name:
        type: string
        required: true
        description: Name of the job

permissions:
  contents: write

jobs:

  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Run test
        run: echo "Test running"
