name: Website Workflow

on:
  workflow_call:

  push:
    branches: [ main ]
    paths:
      - '!src/**'
      - 'website/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
    paths:
      - '!src/**'
      - 'website/**'
      - 'README.md'

permissions:
  contents: write

jobs:

  docs:
    runs-on:  ubuntu-latest
    steps:
      - name: Run website
        run: echo "Website running"
