name: Website Workflow

on:
  workflow_call:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

permissions:
  contents: write

jobs:

  check-modified-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v26.1
      with:
        files: |
          website/**
#        files_ignore: |
#          *.yml

    - name: List modified files
      run: |
        echo "Modified files:"
        for file in ${{ steps.changed-files-specific.outputs.all_modified }}; do
          echo "$file"
        done

    - name: Run step if only the files listed above change
      if: steps.changed-files-specific.outputs.only_modified == 'true'
      run: |
        echo "::set-output name=modified_files::${steps.changed-files-specific.outputs.all_modified}"

  docs:
    runs-on:  ubuntu-latest
    needs: check-modified-files
    if: needs.check-modified-files.outputs.modified_files
    steps:
      - name: Run website
        run: echo "Website running"
      - name: List files
        run: |
          for file in ${{ needs.check-modified-files.outputs.modified_files }}; do
            echo "$file was modified"
          done
